# Generated by Django 5.1.3 on 2024-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='passenger_capacity',
            field=models.IntegerField(),
        ),
    ]
